version:           '2'

services:

    web:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ../loginlogger:/app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - "php"

    php:
        build: "./php"
        volumes:
          - ../loginlogger:/app
        links:
          - "mysql"

    mysql:
      image:  mysql:latest
      environment:
        - "MYSQL_ROOT_PASSWORD=mysqlrootpassword"
        - "MYSQL_DATABASE=mysqldb"
        - "MYSQL_USER=mysqluser"
        - "MYSQL_PASSWORD=mysqlpassword"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - "MYSQL_USER=mysqluser"
        - "MYSQL_PASSWORD=mysqlpassword"
        - "MYSQL_ROOT_PASSWORD=mysqlrootpassword"
      ports:
        - "8080:80"
      links:
        - "mysql:db"
